### ISSUE TITLE
Crash when going from Lantea to Overworld.

### ISSUE THREAD

**Issue by craft90** [Povstalec/StargateJourney#1]
Hi! I tried out your mod. Nice work so far! But I'd run into an issue when attempting to return back to the Overworld from Lantea. I have attached the crash log.

[crash-2023-01-20_01.17.03-client.txt](https://github.com/Povstalec/StargateJourney/files/10462160/crash-2023-01-20_01.17.03-client.txt)

**Comment by Povstalec** [comment]
Ahh, another issue with 8 chevron addresses.
I'm not exactly going to fix this specific bug, since I'm in the process of rewriting the whole Stargate Network to work better with 8 chevron addresses.

**Comment by craft90** [comment]
I know you closed this issue, but I'd like to add some extra context if you don't mind. Initially I used the address provided on the CurseForge page. That caused the two first crashes. I then tried the intergalatic address you get via the address command. Sure, the game did crash again. However when I logged back on the gate was open so I could get back to the Overworld. I don't know how useful this info is but maybe it can help some. Thanks for responding.

**Comment by Povstalec** [comment]
Yes, this helps. I've looked into it a bit and it seems it might actually be some weird client-side quirk I added when I changed how the Pegasus gate ticks. So I've got a fix for it that should work with the new Stargate Network. But thanks for your additional info, that really confirms it's just client-side.
