### ISSUE TITLE
Portals to different portal in same dimensio

### ISSUE THREAD

**Issue by Sjitzooi** [Povstalec/StargateJourney#114]
Though i suspect this isnt going to be added, but is it possible to add a feature where you can connect to another existing portal in the same dimension. 

I am aware that transport rings do this (if you are adding them that is) but i was wondering if it was possible with the standard gates, because i would love to be able to use a stargate as a way to connect to different parts of my world (in the same and other dimensions)

**Comment by kittycat2002** [comment]
This can currently be done by dialing it's 9-chevron address, you can get this address by shift+right clicking the stargate with a pda.

**Comment by lukaskabc** [comment]
7-chevron address - solar system (one or more dimensions) in your galaxy
8-chevron address - solar system in other galaxy
9-chevron address - specific stargate
check wiki: https://github.com/Povstalec/StargateJourney/wiki/Stargate-Network
