### ISSUE TITLE
Redstone activation: HOW?!

### ISSUE THREAD

**Issue by Xeonis** [Povstalec/StargateJourney#121]
Hello, I couldn’t install CC:Tweaked, and I decided to try to activate the portal automatically with redstone, and I had a question about how to count the zero of the circle, 
1) is it possible to add a setting for "Interfaces" to control the first chevron,
2) add more functionality for interfaces
3) write its redstone output mode into its interface

3) Or parse the library of interaction with the portal for the OpenComputers mod

**Comment by lukaskabc** [comment]
Interfaces can provide redstone feedback about the gate state (for example, Milky Way stargate ring rotation).
https://lukaskabc.github.io/StargateJourney/mechanics/stargate_network/interface/

dialing with redstone:
https://lukaskabc.github.io/StargateJourney/survival/dialing/#manual-dialing-with-redstone

To determine that the Point of Origin symbol (zero) is under the top chevron, you need an interface in the `ring segment` mode that outputs a signal of strength **five** and second interface in `ring rotation` mode, which outputs a signal of strength **one**

Note, that only Milky Way stargate can be dialed with redstone.
