### ISSUE TITLE
One way killin

### ISSUE THREAD

**Issue by Xeonis** [Povstalec/StargateJourney#123]
having installed 2 portals in one world and launched one using redstone, I encountered a problem - in one direction the portal works perfectly, but in the other it kills, I tried to rearrange the portal, I thought something was in the way, removing portals in this world did not help, it doesn’t matter which world you are teleporting from and from which portal the code was dialed in one direction you pass through from the caller’s side, on the other side the portal kills you when you try to pass through it

**Comment by lukaskabc** [comment]
>Travel through a Stargate is strictly one-way: from the dialing gate to the receiving gate.
[Stargate fandom](https://stargate.fandom.com/wiki/Stargate)

To go back, you must dial the gate again with the address of the gate you came from.  
That's how Stargates work, according to the lore.

However, you can change this in config.
```toml
#ENABLED - Two way travel possible; CREATIVE_ONLY - Two way travel limited to Players in Creative Mode; DISABLED - Two way travel impossible
#Allowed Values: ENABLED, CREATIVE_ONLY, DISABLED
two_way_wormholes = "CREATIVE_ONLY" # change to "ENABLED"
```

**Comment by Xeonis** [comment]
strange, my memories of the series don't remember this, thanks
