### ISSUE TITLE
Passing back in a Gate kills you ?

### ISSUE THREAD

**Issue by Steepy12** [Povstalec/StargateJourney#126]
I'm testing the mod, and it's absolutely fantastic! However, I'm not sure if this is a bug or not. I used my gate to go to Abydos, passed through the gate, but forgot my pickaxe. So, I went back through the portal and got instantly killed. Is that normal?

**Comment by lukaskabc** [comment]
yes, thats how stargates work
https://github.com/Povstalec/StargateJourney/issues/123
