### ISSUE TITLE
[1.19.2 Hotfix] Archeologist villager doesnt offer map to the ring of gods trade 

### ISSUE THREAD

**Issue by amogus694201** [Povstalec/StargateJourney#13]
Got a archeology villager to master, (the game froze for ~1 minute) but the villager didn't give the trade. Tried again 2 times in creative but the same result, the last trade is the bone for emerald one (expert one).

![image](https://github.com/Povstalec/StargateJourney/assets/126696715/80895ecd-5927-40ec-97e0-b10d4bde09e4)

**Comment by amogus694201** [comment]
I believe its because theres no burried stargate nearby, since in another world it works.

**Comment by amogus694201** [comment]
Does the mod add burried stargates after the world generates?

**Comment by amogus694201** [comment]
Ill try adding the  common stargates datapack since i added the mod after i generated the world

**Comment by amogus694201** [comment]
Doesnt fix it, but theres stargates now

**Comment by Povstalec** [comment]
> I believe its because theres no burried stargate nearby, since in another world it works.

Yup, it does mean there is no buried Stargate nearby.
I most likely won't be fixing this one as the whole Villager system isn't all that fun and finding the Stargate will be getting a rework eventually.

But a quick solution for it is leveling up the Villager around the X = 0 and Z = 0 coordinates, as by default the Stargates can only generate 64 chunks away from the center of the world.

**Comment by Povstalec** [comment]
> Does the work around work if the mod was added after world gen? I am playing all the mods 9 and I am not sure when the mod got added but I am finding the structures with ring gates and idols but i can not get a ring of the gods map to be bought,

The gate structure can only be generated in new chunks, so chances are you've already loaded the chunks in which it was supposed to generate. There is a way to [move the area in which a Stargate structure can generate](https://github.com/Povstalec/StargateJourney/wiki/Troubleshooting#i-added-the-mod-to-an-existing-world-and-the-stargate-isnt-generating), however that is only available in v0.6.8 and up, while All The Mods 9 is using v0.6.7 at the moment.

**Comment by Silentkills** [comment]
Alright. Thank you, I'll look for that update

**Comment by Povstalec** [comment]
Alright, so thanks to tehgreatdoge on Discord, I've added a fix that should hopefully make the map trade work as long as the Stargate exists in the world, no matter how far away the Villager is.

It'll be available in v0.6.9
