### ISSUE TITLE
Checking for PoO not, the Permanent Symbol set

### ISSUE THREAD

**Issue by cookta2012** [Povstalec/StargateJourney#130]
https://github.com/Povstalec/StargateJourney/blob/a2203f0c0d775bd3ea590730356770fc175d3a32/src/main/java/net/povstalec/sgjourney/client/models/AbstractStargateModel.java#L50-L96

Specifically L84

**Comment by cookta2012** [comment]
if(stargateVariant.symbols().permanentPointOfOrigin().isPresent())
            return Optional.ofNullable(symbolRegistry.get(stargateVariant.symbols().permanentSymbols().get()));

should be

if(stargateVariant.symbols().permanentSymbols.isPresent())
            return Optional.ofNullable(symbolRegistry.get(stargateVariant.symbols().permanentSymbols().get()));

**Comment by Povstalec** [comment]
Fixed
