### ISSUE TITLE
custom dimensions don't utilise stargate (only utilise the buried)

### ISSUE THREAD

**Issue by electikos** [Povstalec/StargateJourney#134]
Hello, Povstalec your mod is great, but when I add a new dimension and dial it, it say that stargate is obstructed.

to reproduce the bug download my modified version of stargate journey [Uploading Stargate Journey-1.20.1-0.6.31.jar.zip…]() rename it "Stargate Journey-1.20.1-0.6.31.jar" then dial   7 , 6 , 5 , 4 , 3 , 2 
and you should get the error

 
 
relly thank you for your mod Povstalec

**Comment by electikos** [comment]
sorry for my bad English.

**Comment by lukaskabc** [comment]
Hello, the provided link is invalid.
Also, you should not modify the mod and use data packs instead.

Wild guess: you may have used a structure with the gate sealed (like the buried gate, the gate in the nether, the end, or galcio). Those gates need to be found and unsealed first.

**Comment by electikos** [comment]
**thank you for your help,**

but how to spawn pedestal like chulak instead of buried stargate ?

 i do all that is said in the guide and it spawn but when I dial the dimension it said stargate obstructed and when i execute the commande   "   /locate structure #sgjourney:stargate_pedestal    "      it found one.

I now will do with a datapack thank you.

**Comment by Povstalec** [comment]
> but how to spawn pedestal like chulak instead of buried stargate ?

If you only want to generate a pedestal that already exists in the mod, use this part of the Datapack guide, it's as simple as that, no need to do anything custom or edit the mod, just make a tag and add your biomes to it:
https://github.com/Povstalec/StargateJourney/wiki/Datapacks/#making-stargate-pedestals-generate-inside-a-dimension

**Comment by electikos** [comment]
thank you but i already do this.
the gate don't dial but when i teleport in the dimension and /locate a pedestal i locate one unburied.
why ?

**Comment by Povstalec** [comment]
What happens when you try to locate specifically a buried one? Do you still find it? Because if so, that just means both gates are generating and you're unlucky in the fact that buried gate is closer to the center and thus gets located before the pedestal, ending the structure search.

**Comment by electikos** [comment]
yes I found it, what can i do.
can i set black list for buried stargate in my biome.

**Comment by electikos** [comment]
I found how made the blacklist in the buried stargate tag : 
"!sgjourney:**your_biome**"
i join the game and dial the gate, surprisingly it function.
when I /locate a buried stargate in teh custom dimension it dosen't found one.
thank you  **_povstalec_** and  **_lukaskabc_** for your help

**Comment by Povstalec** [comment]
I'm afraid it works not because ! works as a blacklist, but because ! creates a syntax error that prevents the whole file from loading, potentially causing further issues down the line.

**Comment by electikos** [comment]
no it function i can locate a buried stargate on the earth but not on my dimension.
