### ISSUE TITLE
Custom stargate variant

### ISSUE THREAD

**Issue by electikos** [Povstalec/StargateJourney#135]
Hello, can someone explain me how to make stargate variant with the new version ?

**Comment by lukaskabc** [comment]
You can take a look for example on [Jaja's gates](https://github.com/JajaSteele/jajas-gates)

**Comment by Povstalec** [comment]
The Datapacks now only handle registry side of Stargate Variants, the rest of the stuff is now done inside Resourcepacks. Examples of working variants can be found here:

Resourcepack side of things:
https://github.com/Povstalec/StargateJourney/tree/main/src/main/resources/assets/sgjourney/sgjourney/stargate_variant/milky_way

Datapack side of things:
https://github.com/Povstalec/StargateJourney/tree/main/src/main/resources/data/sgjourney/sgjourney/stargate_variant

**Comment by electikos** [comment]
thank povstalec to help,
I tried to do in a resource pack and datapack  even the two at the same time but it still continue to take mylkyway texture.

**Comment by Povstalec** [comment]
Do you have a place where you could show your resourcepack + datapack? I'm gonna need to see the files in order to help any further.

**Comment by electikos** [comment]
I send you something one mail.

**Comment by electikos** [comment]
I finally create a variant that work.
thank for helping me to do it, I will make a mod like moregate to add new variant.
thank very much
