### ISSUE TITLE
[1.19.2 Hotfix] Active stargate sound looping indefinitely, causing game sounds to stop working

### ISSUE THREAD

**Issue by logicsequence** [Povstalec/StargateJourney#15]
I've noticed that after activating a gate, the looping background sound sometimes stays on, and when that occurs all other game sounds, including UI clicks, etc., are completely disabled.

**Comment by Povstalec** [comment]
This is interesting as it has never happened to me while testing (though I didn't really test everything on 1.19.2). Do you know how to replicate the bug?

**Comment by logicsequence** [comment]
Yes, it might be specific to me, i don't know, but all i have to do is dial the stargate a few times and eventually one of the chevron lock sounds won't play while dialing, once that happens it's hit-or-miss on whether or not the remaining chevron lock sounds will play.  If the last lock sound plays then everything is fine, but if it doesn't then the game sounds just stop completely and only the active stargate loop sound can be heard (even if you turn them off) until you completely exit minecraft and restart it. *Caveat* all the sounds IN an open game won't work, the main menu sounds will work, but nothing in a game, until you restart.

**Comment by logicsequence** [comment]
Would you like a video of the bug occurring?

**Comment by Povstalec** [comment]
Okay, so I've tried changing some stuff in 0.6.6, hopefully that helped

> Would you like a video of the bug occurring?

But in case it didn't help, then yes, a video would be helpful

**Comment by Povstalec** [comment]
Closing this because no one reported this being an issue after I re-did some of the sounds. If the issue happens to someone in the future, do feel free to re-open it.
