### ISSUE TITLE
[Suggestion] Masking stargates

### ISSUE THREAD

**Issue by slava110** [Povstalec/StargateJourney#17]
In AUNIS mod (only available for 1.12) you could've used blocks on stargate to mask it. This way people were able to make awesome platforms for the mod or just place it into the ground a bit.
![sddefault](https://github.com/Povstalec/StargateJourney/assets/26705162/6581e7ec-152f-4922-8755-7911fc625699)
I think this mechanic could be implemented in this mod and reimagined a bit.
Instead of masking only bottom blocks like in AUNIS maybe all blocks should be maskable? With that buried stargates will actually be in sand.
What do you think?

**Comment by Povstalec** [comment]
It is done.
