### ISSUE TITLE
Stargate DHD can have snow block on it

### ISSUE THREAD

**Issue by slava110** [Povstalec/StargateJourney#18]
![image](https://github.com/Povstalec/StargateJourney/assets/26705162/2d5c6cae-2769-45ab-8dd6-7c7c967eace6)
I think it shouldn't be able to sustain snow block

**Comment by Povstalec** [comment]
Yup, I definitely need to fix this

**Comment by WinMister332** [comment]
That said, a DHD can have snow on it, just look at the Beta gate's DHD when Carter and O'neill got sent to the Beta gate, it had snow on-top of it's DHD, it make sense if a DHD was out in the open during a snow-storm it'd collect snow. I say keep it, turn it into a feature.

**Comment by Povstalec** [comment]
> That said, a DHD can have snow on it, just look at the Beta gate's DHD when Carter and O'neill got sent to the Beta gate, it had snow on-top of it's DHD, it make sense if a DHD was out in the open during a snow-storm it'd collect snow. I say keep it, turn it into a feature.

It might actually be a cooler idea to have a way to apply some kind of overlay to the DHD instead of a flat snow layer

**Comment by slava110** [comment]
Would be cool but not sure if you want to deal with it. Minor thing, up to you c:
