### ISSUE TITLE
Computercraft Examples

### ISSUE THREAD

**Issue by Herobr1ne** [Povstalec/StargateJourney#22]
Hey, 
I want wo ask if its possible for you to post some computercraft examples? Maybe a lua script that calls a specific address. 
I have problems to create some cause i dont find any examples yet for this mod.

**Comment by Povstalec** [comment]
I have one (not exactly great, but working) example specifically for Milky Way gates [here](https://github.com/Povstalec/StargateJourney-ComputerCraft-Programs/blob/main/StargateDialing.lua)

The other gates are much simpler to dial with computers in comparison, since all that's needed to dial is to use the engageSymbol() method multiple times in a row.

**Comment by MarobsKoco** [comment]
Really nice, But how can u open the portal without the use of an dhd to push the button? I cant to seem to open the portal with cc: tweaked. How could wwe do that?

**Comment by Povstalec** [comment]
> Really nice, But how can u open the portal without the use of an dhd to push the button? I cant to seem to open the portal with cc: tweaked. How could wwe do that?

By encoding the Point of Origin, which is Symbol 0. Basically, the same steps you've done to encode the whole other Symbols of the Address you repeat for 0.

**Comment by MarobsKoco** [comment]
Thnx, is that the same for the other galaxy's? As i remember in the series and movies they have an other point of origin, Like when i want to go to pegasus galaxy with the milkyway portal? Still use the 0 at the end ?

**Comment by Povstalec** [comment]
Nope, the Point of Origin was always for Extragalactic Addresses even in the show. The extra Symbol is actually a prefix at the start of the Address.

Mechanic-wise, the entire Address changes when dialing, so for example the Earth Address which is normally -27-25-4-35-10-28- becomes -1-35-4-31-15-30-32- (both are based on the Addresses shown in the show) but as in general, I give all the Extragalactic Addresses in the same Galaxy the same prefix, so all Extragalactic Addresses for Milky Way planets start with 1 and for Pegasus with 18.

The Extragalactic Address for Lantea itself is -18-20-1-15-14-7-19-

**Comment by Povstalec** [comment]
Oh wow, that's quite an impressive program
