### ISSUE TITLE
Overworld SG spwn ground level

### ISSUE THREAD

**Issue by Kettumasa** [Povstalec/StargateJourney#24]
Im on ATM9 and the portals spawn above ground so the Cartouches dont spawn and im unable to access the Abydos.

**Comment by Povstalec** [comment]
> Im on ATM9 and the portals spawn above ground so the Cartouches dont spawn and im unable to access the Abydos.

ATM9 should also be running the Common Stargates Datapack, which should also be making Cartouche Structures spawn around the world (as long as the mod version is 0.6.8 and above)
