### ISSUE TITLE
small lag issue

### ISSUE THREAD

**Issue by roughdayOG** [Povstalec/StargateJourney#26]
the stargates are constantly sending ping requests to other stargates when not even activated. it isn't bad when the mod is by itself but when in a pack like ATM9 and on a server with 10+people when we all place and load a star gate the server starts to brick TPS.

**Comment by Povstalec** [comment]
> the stargates are constantly sending ping requests to other stargates when not even activated.

Wait, what do you mean by that? Can you elaborate on what you've measured? Because I honestly don't remember making the Stargates communicate when they're not even active.

**Comment by Povstalec** [comment]
Closing this due to a lack of information. Might reopen if more information regarding this surfaces.
