### ISSUE TITLE
no gate at target system

### ISSUE THREAD

**Issue by elvisinthehood** [Povstalec/StargateJourney#28]
Might be a ATM 9 issues  but I have run into a few gate locations where it says no gate at target destination

**Comment by Povstalec** [comment]
Most likely not a bug. Every dimension has an address, but most dimensions won't have a Stargate by default. The only ones that will generate a Stargate are dimensions from sgjourney + Overworld. (ATM9 also has them generate in Nether and End I think).

If you want to want to travel through a Stargate to those dimensions, you'll have to bring one there yourself. That way the intended progression of other mods is left untouched.

Although if you specifically want Stargates to generate in some modded dimensions, I have a [guide](https://github.com/Povstalec/StargateJourney/wiki/Guides#adding-a-dimension-to-stargate-network) for that too.
