### ISSUE TITLE
Models Not Found

### ISSUE THREAD

**Issue by pietro-lopes** [Povstalec/StargateJourney#30]
Models referenced here: https://github.com/Povstalec/StargateJourney/blob/main/src/main/resources/assets/sgjourney/blockstates/naquadah_generator_mark_i.json#L3-L4 and here https://github.com/Povstalec/StargateJourney/blob/main/src/main/resources/assets/sgjourney/blockstates/naquadah_generator_mark_ii.json#L3-L4 do not exists

And lots of other like blockstates and other models, just check logs.
Also missing sound files.

**Comment by Povstalec** [comment]
Yes, I am well aware. The stuff that's missing is simply unfinished.
