### ISSUE TITLE
Stargates should be partially recharged when struck by lightning

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [Povstalec/StargateJourney#37]
i don't remember the name of the episode but sg1 did this,
also gates should function as lightning rods.

**Comment by Povstalec** [comment]
Ah The Torment of Tantalus episode, yes. Although I don't think the gate itself should function as a lightning rod (since putting an actual lightning rod is easy already), I do think it would be a nice mechanic to have it recharge through lightning.
