### ISSUE TITLE
cant dial same solar system 

### ISSUE THREAD

**Issue by Mikecolle** [Povstalec/StargateJourney#39]
i have the data pack in the datapack folder and it still wont let me dial same planet

**Comment by Povstalec** [comment]
That's not how the datapack works. It makes the game **generate** more Stargates in the same dimension, you always had the ability to dial the same planet.

As for why you can't dial the same planet, you can, but you **need** to use the [9-Chevron Address](https://github.com/Povstalec/StargateJourney/wiki/Stargate-Network#addresses).
