### ISSUE TITLE
CC:tweaked broken code

### ISSUE THREAD

**Issue by JonFoxy** [Povstalec/StargateJourney#42]
No matter what I try i always **_always_** get "attempt to call global '[code here]' (a nil value)" and me being someone who's coded in C#, Java, Javascript, and Python (I despise lua for its dated and very very different coding structure). I cant figure out why none of the codes are working. I wanted to try modifying the stargateDialing code you gave and I always get that error. And nothing happens 

For context. I am using a basic interface connected to a Milky Way Stargate with CC Advanced computer with wired modem on same modem network. and even tried **_POWERING_** the interface to no avail

**Comment by tehgreatdoge** [comment]
That sounds like you didn't connect the peripheral properly / update its name in the code? Can't help much beyond that as you didn't give much context

**Comment by JonFoxy** [comment]
I gave all the context needed. Peripherals connected. Network connected. Code just breaks

**Comment by Povstalec** [comment]
> No matter what I try i always **_always_** get "attempt to call global '[code here]' (a nil value)" and me being someone who's coded in C#, Java, Javascript, and Python (I despise lua for its dated and very very different coding structure). I cant figure out why none of the codes are working. I wanted to try modifying the stargateDialing code you gave and I always get that error. And nothing happens

Would you mind sending some of the code you've changed plus an in-world screenshot of the Stargate Interfacing setup you are using?

**Comment by C4PTRAMPAGE** [comment]
i've noticed that if you attach an interface on an existing stargate everything works fine but if you place the peripheral first then put the gate on it functions wont work.

that might be the cause of this issue.

**Comment by Povstalec** [comment]
> i've noticed that if you attach an interface to an existing stargate everything works fine but if you place the peripheral first then put the gate on it functions wont work.

Gonna close the whole issue then, since I'm 99% sure I fixed this exact problem in 0.6.19
