### ISSUE TITLE
getChevronsEngaged() function improvement

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [Povstalec/StargateJourney#45]
I'm sorry but your probably going to hear from me a lot... i'll try not to post too often, and thanks for listening to my other ideas.

It would be nice if getChevronsEngaged() could return parameters for the symbol every chevron has encoded, so someone can for example write:

count, chev1, chev2, chev3, chev4, chev5, chev6, chev7, chev8, chev9 = getChevronsEngaged()
print(count .. " - " .. chev1 .. " " .. chev2 .. " " .. chev3 .. " " .. chev4 .. " " .. chev5 .. " " .. chev6 .. " " .. chev7 .. " " .. chev8 .. " " .. chev9)

and get: 7 - 27 25 4 35 10 28 0 nil nil

**Comment by Povstalec** [comment]
No worries about posting often, it's good to see other people's perspectives.

Yes, this is a good idea, but I don't think I want it to be a part of something the Basic Interface should be able to do. So along with the rest of the more advanced functions planned, it could be a separate function of an advanced form of Interface.

Maybe something like getSymbolAtChevron(chevronNumber)

**Comment by C4PTRAMPAGE** [comment]
yeah that works to.

hey since the mod tracks a bunch of stuff about the gates anyway, have you thought about adding random npc attacks through the gate if its been opened/loaded enough? jaffa/wraith/etc.

**Comment by Povstalec** [comment]
Yes, I have. First however I will have to learn how Entity AI works to add stuff like that.

**Comment by Povstalec** [comment]
Not sure if it's exactly what you had in mind, but there's now the getDialedAddress() and getConnectedAddress() that will tell you the address as an array

**Comment by C4PTRAMPAGE** [comment]
sorry, yeah i forgot to close the issue after you added that

**Comment by Povstalec** [comment]
Okay, cool
