### ISSUE TITLE
computercraft pegasus stargate symbol set override

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [Povstalec/StargateJourney#47]
if you have time for this it'd be cool of you could add something like symbolSetOverride(symbolSetName) to change the symbols displayed on a pegasus stargate.

also a bit of feedback, i really think universe gates should need to be rotated with computers like milky way ones but instead of raise and lower it should just be encodeChevron() it just seems too easy and a bit weird to control a gen 1 gate like its a much more advanced gen 3.

if you dont mind me asking, are you planning to change pegasus gates to instantly lock chevrons from dhd control? also are you planning to add a universe dhd and/or remote? thanks.

**Comment by Povstalec** [comment]
> if you have time for this it'd be cool of you could add something like symbolSetOverride(symbolSetName) to change the symbols displayed on a pegasus stargate.

Being able to change symbols on the Pegasus gate sounds like an awesome idea, definitely adding that.

> also a bit of feedback, i really think universe gates should need to be rotated with computers like milky way ones but instead of raise and lower it should just be encodeChevron() it just seems too easy and a bit weird to control a gen 1 gate like its a much more advanced gen 3.

Regarding the Universe gates, yes, I also think it should be a bit more complicated to dial them. The plans are to have each gate be a bit different when it comes to dialing and maybe also add manual dialing to the Universe Stargates (although I'm gonna need to get a looped rotation sound for that).

> if you dont mind me asking, are you planning to change pegasus gates to instantly lock chevrons from dhd control? also are you planning to add a universe dhd and/or remote? thanks.

There isn't really a plan for instantly locking chevrons from DHD, as that never happened in the show. The Pegasus gates always rotated. However I have started working on something that skips the dialing entirely and immediately starts a connection without a kawoosh, based on that dialing device the Asgard used.

And yes, I do plan on adding the Universe Dialing Remote as well as a few other blocks/items for dialing.

**Comment by C4PTRAMPAGE** [comment]
> There isn't really a plan for instantly locking chevrons from DHD, as that never happened in the show. The Pegasus gates always rotated.

huh, guess its been too long since i watched sga then.

anyway yeah, i'm sure figured it by now that i'm writing a dhd program, the gui is based on windows 95 and yes it has a blue screen easter egg, the plan to put it up on pastebin once its in a releasable state, would you like me to send you the link once its up so people have an easy to use dialing program on the mod page? though before you answer that you should know the blue screen easter egg (its a reference to a multiplayer map in halo 2 & 3) is a little bit rude and i'm adamant on not changing it because i think its funny, this is the text in the blue screen:
```
A total FU exception has occurred at your location.
All system functionality will be terminated.
*Press any key to power cycle the system.
If the system does not restart; scream at the
top of your lungs and pound the keypad.
Press any key to continue_
```

**Comment by Povstalec** [comment]
Yeah, sure, I don't mind linking your dialing program, sounds like a fun easter egg too.

**Comment by C4PTRAMPAGE** [comment]
cool, thanks!
