### ISSUE TITLE
1.20.1 Crash on world generation (0.6.9+)

### ISSUE THREAD

**Issue by jburrows82** [Povstalec/StargateJourney#50]
`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22245_(net.minecraft.world.entity.ai.attributes.Attribute)" because "this.f_22141_" is null
`

on world generation.  0.6.8 Hotfix gens fine. Tested with *.9 & *.10  and both Forge 47.2.19 & Neoforge 47.1.84

[debug.log](https://github.com/Povstalec/StargateJourney/files/13813580/debug.log)
[latest.log](https://github.com/Povstalec/StargateJourney/files/13813581/latest.log)
[crash-2024-01-02_15.00.49-server.txt](https://github.com/Povstalec/StargateJourney/files/13813582/crash-2024-01-02_15.00.49-server.txt)

**Comment by Povstalec** [comment]
Don't know why exactly that happens but I see mixins and I don't like it. I've never had that crash happen on plain sgjourney, but whatever, it's probably gonna be easier to just comment out the stuff surrounding the entity that causes this and leave it for another time.

**Comment by tehgreatdoge** [comment]
Close since the Goauld was commented out and the cause of the issue is known
