### ISSUE TITLE
gravity can kill player via stargate when traveling to cavum tenebrae

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [Povstalec/StargateJourney#57]
if the stargate generates facing the wrong way the gravity of the black hole pulls the player back into the wormhole of the gate killing them.

by the way i couldn't find info on this but i assume cavum tenebrae is p3w-451?

**Comment by Povstalec** [comment]
Alright, I fixed the problem by always making Stargate Pedestals face north.

> by the way i couldn't find info on this but i assume cavum tenebrae is p3w-451?

Yeah, kinda. I've taken lots of liberties with its design to make it more geographically interesting, but it was the general idea.

**Comment by Povstalec** [comment]
Okay, now the pedestal has been altered cause player to fall down and Stargates will now give players just enough momentum to force them out, which means the player won't be pulled back into the wormhole
