### ISSUE TITLE
Crash on world creation starting from sg 6.12 1.20.1

### ISSUE THREAD

**Issue by Tomat777** [Povstalec/StargateJourney#60]
[crash-2024-01-14_09.14.24-server.txt](https://github.com/Povstalec/StargateJourney/files/13930669/crash-2024-01-14_09.14.24-server.txt)
[latest.log](https://github.com/Povstalec/StargateJourney/files/13930670/latest.log)
[debug.log](https://github.com/Povstalec/StargateJourney/files/13930671/debug.log)

**Comment by tehgreatdoge** [comment]
Seems to be from an outdated common stargates datapack. Did you update from <0.6.9?

**Comment by Tomat777** [comment]
Yep that was it, thanks
