### ISSUE TITLE
0.6.17 crash on startup both client and server

### ISSUE THREAD

**Issue by DelviousCrafts** [Povstalec/StargateJourney#64]
Both client and server will crash on startup with the latest SG Journey installed with the following crash logs. Latest logs are also provided for assistance.

Client Logs:
- [Crash Report](https://gist.github.com/DelviousCrafts/d8e8d82a44153cdc3f2732e44c69ed2e)
- [Latest Log](https://gist.github.com/DelviousCrafts/0492afa320490a2932a2f65cc3c2f8af)

Server Logs: 
- [Crash Report](https://gist.github.com/DelviousCrafts/d2a7b0873a56b9537867494e1cf3b3d9)
- [Latest Log](https://gist.github.com/DelviousCrafts/a68e9325592070888c5adef795646535)

Versions: 
- Minecraft: 1.20.1
- Forge: 47.2.19
- SG Journey: 0.6.17

**Comment by Povstalec** [comment]
Already fixed, in 0.6.17 hotfix, the mod file just didn't compile properly for some reason. It was fine after recompiling.
