### ISSUE TITLE
"Stargate does not have enugh space"

### ISSUE THREAD

**Issue by Affe36963** [Povstalec/StargateJourney#68]
Every time I open any applied energistics 2 interface i get the message "Stargate does not have enugh space" above my hotbar.
This started when I put a stargate in my base but it still appers there even if I remove the stargate.
info: All the mod 9
Stargate journey-1.20.2-0.6.19

**Comment by Povstalec** [comment]
I'm aware of this issue, but still have no idea what interaction with AE2 could possibly be causing it.

**Comment by AshleighTheCutie** [comment]
It's not AE2, I think it's JEI. Everytime I hover on a functional SG block (as in, something with a GUI or a Cartouche / the gamtes themselves) in JEI or my inventory, it happens. AE2 is present but it happens everywhere, not just there.

**Comment by Povstalec** [comment]
> It's not AE2, I think it's JEI. Everytime I hover on a functional SG block (as in, something with a GUI or a Cartouche / the gates themselves) in JEI or my inventory, it happens. AE2 is present but it happens everywhere, not just there.

I have JEI as a dependency in my dev environment and I've never seen it happen. What version of Minecraft/Forge/JEI did it happen for you the last time?

**Comment by AshleighTheCutie** [comment]
1.20.1 / NeoForge 47.1.88 / JEI 15.2.0.27

Even better, import [this](https://homesrv.ashleighhost.net/downloads/FTB%20Presents%20Direwolf20%201.20.zip) into Prism (not MultiMC! MultiMC doesn't seem to want to add NF support, and the pack requires it)

**Comment by lukaskabc** [comment]
Tried debugging ATM9 instance
triggered on hover in inventory (over cartouche in this case)

![image](https://github.com/Povstalec/StargateJourney/assets/28897542/c7143268-b66f-439c-831c-48fd4550b499)
dont ask me what is apotheosis doing there... :D

[threads_report.txt](https://github.com/user-attachments/files/15660525/threads_report.txt)
