### ISSUE TITLE
computercraft methods? i'll take your entire stock please.

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [Povstalec/StargateJourney#72]
I'm back to working at the dhd script after some burn out and i noticed that theres not really a good way to get if a connection is incoming or not other than the event, could you add a function for that? idk something like isConnectionIncoming(), and isChevronOpen() would be helpful too.

also, i know stargates are and should be the main focus of the mod but what about methods for the transport rings?
i was thinking something like getRingsInRange() returns an array of ring uuids, and activateRings() expects the uuid of the target rings...thats probably enough in most cases but it may also be useful to have getRingsEnergy() and getEnergyToTransport() expects uuid of the target rings and returns the energy required to send something there (only needed if you make the energy requirement change by distance)

hope I'm not asking too much here, i don't think it'd be difficult or take much time but i don't know how hard it is to add this stuff, I'm working on a mod too but my job is datapack/textures/creative director, one of my friends does the coding, which is why i haven't offered to help yet by the way, not sure how much i could do, and thats the first mod he's made.

**Comment by Povstalec** [comment]
The Stargate function seems like a nice idea, the Transport Rings functions I'll decide on after I change them.

But don't worry about how longs stuff takes, good ideas shouldn't be limited by the time it takes to bring them to life.
