### ISSUE TITLE
more of a question

### ISSUE THREAD

**Issue by Vadewolf** [Povstalec/StargateJourney#73]
y is there no recipes for the jaffa armor? its so cool and all that

**Comment by Povstalec** [comment]
It's fairly easy to get all the pieces as loot if you go explore the different Goa'uld Pyramids on Abydos, so there isn't a direct need to have it craftable. Plus by being limited to Goa'uld temples, it enforces the idea that the armor is directly tied to the Goa'uld.

**Comment by Vadewolf** [comment]
ok makes sense tho i will say needing the amount i need probably wasnt intended lol tysvm tho
