### ISSUE TITLE
Stargate with ATM9 (newest version)

### ISSUE THREAD

**Issue by Belu97** [Povstalec/StargateJourney#75]
hello,

i tried to go with my stargate to a another dimension (end,nether) but it don´t work and i get back "Dialed solar system has no stargates"
had i to pregenerate the chunks that i can open a portal to that ?

i use this list for the coordinates
https://github.com/Povstalec/StargateJourney/wiki/Solar-System#end

**Comment by Povstalec** [comment]
No, nothing like that. By default, Nether and End don't have Stargates, as to not disrupt the Vanilla progression. The fact it was possible before was pretty much just a bug if I remember correctly, unless the ATM9 devs would specifically want Stargates to generate there (which I'm not sure about, but it can totally be done with a simple Datapack). 

You'll first need to place a Stargate there yourself after you get there through Vanilla progression, so just bringing any Stargate you find in the Overworld with you to the Nether and placing it down should work.

**Comment by Belu97** [comment]
where should the datapack be maybe i can go in and read something out

**Comment by Povstalec** [comment]
ATM9 uses kubejs to handle Datapacks, which I'm not very familiar with, but under normal circumstances, Datapacks are tied to individual Minecraft worlds and you can put them in the datapacks folder
https://minecraft.wiki/w/Tutorials/Installing_a_data_pack

The general idea behind making the Stargate in different Dimensions is very simple though, you basically just add the Biomes of said Dimension into a tag which the Stargate structure references when the game generates it.
