### ISSUE TITLE
Tag `sgjourney:wormhole_ignores` does nothing

### ISSUE THREAD

**Issue by Ktlo** [Povstalec/StargateJourney#94]
I want to prevent teleportation for some entity types and I found tag `sgjourney:wormhole_ignores`. I assumed that this tag should do the thing, but it didn't change anything. Moreover the entities that I wanted to add were already listed there (create contraptions entities). Did I get it wrong and tag is used for other reasons?

**Comment by Povstalec** [comment]
The tag is used for the wormhole ignoring entities when it's deciding whether or not it should close automatically, which means it has nothing to do with actual teleportation.

**Comment by Ktlo** [comment]
I see. But shouldn't there be a way to prevent certain types of entities from teleporting? I'm trying to make create trains go throw the star gates, but the `create:carriage_contraption` entity tries to teleport to other dimension. This causes the game to crash when the player enters this dimension.

**Comment by Povstalec** [comment]
Well, I didn't really think of a having certain Entities not get teleported, but sure, if it helps, I can add a tag that will let you specify entities that can't be teleported. Probably gonna call it `#sgjourney:wormhole_cannot_teleport` but check the changelog just to make sure once I release the next version, I usually include info about new tags there if I don't forget about it.

**Comment by Ktlo** [comment]
Thank you in advance!

**Comment by Povstalec** [comment]
Okay, the update with the new tag is out
