### ISSUE TITLE
Stargate did not spawn at the point that the map directs you to.

### ISSUE THREAD

**Issue by DestinyPlayer** [Povstalec/StargateJourney#99]
VERSIONS:
Forge 1.20.1-47.2.0
Stargate Journey-1.20.1-0.6.22
Commom Stargate Pedestals 1.20.1 - 1.2.1

Basically this. I got a villager to sell me the map, but once I arrived at the point it was pointing towards, there was nothing.

I dug all the way from ground to bedrock, nothing. I even dug out the Explorer's Compass and had it point at that exact location as well for "Buried Stargate".

I have two potential guesses as to what could have happened. Either it was because this location was already pre-generated with Chunky, but then I would have expected the Stargate to already be there instead of only generating once you get the map.

The other guess is that Teralith or Galosphere have somehow overridden it, but that would just point to a weird interaction between these two mods.

Console did not say anything conspicuous about it, the only relevant entry being:
`[18:59:32] [Server thread/INFO] [ne.po.sg.StargateJourney/]:
 Attempting to locate Buried Stargate for map`

https://i.imgur.com/pQgARPw.png - Full Modpack

**Comment by lukaskabc** [comment]
Have you checked the location in spectator mode to make sure the gate isn't actually there?

**Comment by DestinyPlayer** [comment]
Wait a second... I finally found it. Nevermind.

APPARENTLY I somehow managed to miss the damn thing even while forcibly digging out entire chunks of terrain via VeinMiner, by quite literally ONE BLOCK.

Apologies for bothering you.
